import { exportTest, value02 } from "./test.js";

export let apiProducts01 = 1


console.log('exportTest constant: ',exportTest, value02)

let apiProducts = []

document.addEventListener('DOMContentLoaded', () => {
    const contentDiv = document.querySelector('.content'); //catch the element in HTML which will be fullfilled with the next information automatically generated by the JS 

    fetch('https://dummyjson.com/products', {}) //fetch the information from an API or JSON archive
        .then((response) => { 
            if (!response.ok) { //make a validation
                throw new Error('Newtwork response was not ok')
            }
            return response.json() //transform the information to JSON format
        })
        .then((jsonData) => { //Now, with the information transformed, do the next thing 
            
            const apiData = jsonData //Put the information inside a constant to do anything we want with it
            console.log('apiData stored in the const "ApiData": ', apiData) //print in the console just to see how the information was stored to facilitate to working on it

            console.log(
                'just the first object: ',
                apiData.products[0],
                apiData.products[1],
                ) // testing the extract a part of the fetched information
            
            apiProducts = apiData.products
            
            console.log('const "apiProducts": ', apiProducts)

            let i =0; //creating a variable to numerate the list of the information fetched

            apiProducts.forEach((item) => { //do something with each item of the information
                const dataElement = document.createElement('div')
                dataElement.classList.add("card") //create a 'div' element to use inside the HTML content
               /*  console.log('item: ', i++, ' ', item)//print each item and sum 1 to the 'i' variable */
                dataElement.innerHTML = ` 
                    <div class='product__id' > ID: ${item.id} </div>
                    <header class='product__title'> ${item.title} </header>
                    <div class='product__brand' > ${item.brand} </div>                    
                    <img class='product__image' src = "${item.images[0]}">                    
                    <div class='product__price' > R$ ${item.price} </div>
                    <div class='product__description' > ${item.description} </div>                                                          
                `;//most important part which receives the 'html' information the automatically generate with the variables inside the '${variables}'
                contentDiv.appendChild(dataElement) //append the information to the HTML id 'content' stored in the 'contentDiv' constant
            });
        })
        .catch(error => console.log('ERROR Fetching data', error));//guaranteee to return a message with the current error if that is the case
}) 